version: '3.8'
services:
  db-run-migrations:
    container_name: 'nft-oracle-db-run-migrations'
    image: 'nft-oracle.backend'
    hostname: db-run-migrations
    networks:
      - nft-oracle-local-net
    volumes:
      -  ../../src/backend/.env:/usr/src/app/.env
    command: [ "yarn", "typeorm:run" ]

networks:
  db-net:
    driver: bridge
    name: nft-oracle-local-net
  nft-oracle-local-net:
    external: false
    driver: bridge
    name: nft-oracle-local-net