#! /bin/bash

nest build

files=($(grep -r --include='*.js' 'backend/src' ./dist | sed 's/:/ /g' | awk '{ print $1 }'))
for index in ${!files[*]}
do
    file=${files[$index]}
    cat ${file} | sed "s|/src/|/dist/|g" >> ${file}.changed && mv ${file}.changed ${file}
done