version: '3.8'
services:
  nft-oracle-backend-json-api:
    container_name: 'nft-oracle-backend-json-api'
    image: 'nft-oracle.backend'
    hostname: nft-oracle-backend-json-api
    networks:
      - nft-oracle-local-net
    volumes:
      - ../../src/backend/.env:/usr/src/app/.env
    environment:
      - HTTP_PORT=${BACKEND_HTTP_API_PORT}
    ports:
      - 9000:3000
    command: [ "node", "./dist/applications/json-api/main.js" ]

  nft-oracle-backend-json-rpc:
    container_name: 'nft-oracle-backend-json-rpc'
    image: 'nft-oracle.backend'
    hostname: nft-oracle-backend-json-rpc
    networks:
      - nft-oracle-local-net
    volumes:
      - ../../src/backend.env:/usr/src/app/.env
    environment:
      - HTTP_PORT=${BACKEND_HTTP_RPC_PORT}
    ports:
      - 9001:3000
    command: [ "node", "./dist/applications/json-rpc/main.js" ]

  nft-oracle-frontend:
    container_name: 'nft-oracle-frontend'
    image: 'nft-oracle.frontend'
    hostname: nft-oracle-frontend
    networks:
      - nft-oracle-local-net
    env_file:
      - ../../src/frontend/.env
    volumes:
      - ../../src/frontend/.env:/usr/src/app/.env
    ports:
      - 4000:8000
    command: [ "yarn", "start" ]

networks:
  nft-oracle-local-net:
    external: false
    driver: bridge
    name: nft-oracle-local-net